// <auto-generated />
// Este archivo es generado automáticamente por EF Core.
// Representa el "snapshot" del modelo actual de base de datos
// usado para comparar cambios en futuras migraciones.

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BackendCConecta.Infraestructura.Persistencia;

// Importamos el DbContext principal del proyecto
using BackendCConecta.Infraestructura.Persistencia.Configuraciones;

#nullable disable

namespace BackendCConecta.Migrations
{
    // Se indica que este snapshot representa el modelo para AppDbContext
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        // Este método describe la estructura actual del modelo en C#
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Información general del proveedor usado y reglas de longitud de identificadores
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17") // Versión de EF Core usada
                .HasAnnotation("Relational:MaxIdentifierLength", 128); // Máximo largo para identificadores

            // Indica que se usará incremento automático (IDENTITY) para claves primarias en SQL Server
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // 📌 Definición de entidad: Anuncio
            modelBuilder.Entity("BackendCConecta.Dominio.Entidades.Anuncio", b =>
            {
                // 🔹 Propiedad: Id (clave primaria, auto-generada)
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd() // Identity (auto-incremental)
                    .HasColumnType("int"); // Tipo de columna SQL

                // Refuerza que esta columna sea Identity para SQL Server
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                // 🔹 Propiedad: Descripcion (requerida)
                b.Property<string>("Descripcion")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                // 🔹 Propiedad: FechaPublicacion (tipo datetime2)
                b.Property<DateTime>("FechaPublicacion")
                    .HasColumnType("datetime2");

                // 🔹 Propiedad: Titulo (requerida)
                b.Property<string>("Titulo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                // 🔹 Clave primaria
                b.HasKey("Id");

                // 🔹 Nombre de la tabla en SQL Server
                b.ToTable("Anuncios");
            });

#pragma warning restore 612, 618
        }
    }
}
